name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: pre-install
      run: sudo apt update && sudo apt upgrade
    - name: build
      run: cd gbvm && make virex && cd ..
