version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_install:
      - sudo apt update && sudo apt install -y build-essential
    build:
      - cd gbvm && make virex && cd ..
