version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - cd gbvm && make virex && cd ..
    - cd Documentation && mkdocs build && cd ..

mkdocs:
  configuration: Documentation/mkdocs.yml

python:
  install:
      - requirements: Documentation/requirements.txt
