version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - cd gbvm && make virex && cd ..
    - echo "Installing requirements..."
    - pip install -r Documentation/requirements.txt
    - echo "Running MkDocs manually..."
    - mkdocs build -f Documentation/mkdocs.yml

mkdocs:
  configuration: Documentation/mkdocs.yml

python:
  install:
    - requirements: Documentation/requirements.txt
