version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: Documentation/mkdocs.yml

python:
  install:
      - requirements: Documentation/requirements.txt

build:
  commands:
    - cd gbvm && make virex && cd ..
    - echo "Running MkDocs manually..."
    - mkdocs build -f Documentation/mkdocs.yml
